# trigger:
# - master

variables:
  subscription: IoT UAE(19dba8f7-7dcd-4a79-8aea-7594b47f7b8b)
  resourceGroup: resourcegroup-tfstate
  storageAccount: saterraformtfstateskip
  container: tfstate
  tfstateFile: terraform.tfstate
  anyTfChanges: false

pool:
  name: self-hosted

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
    

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'IoT UAE (19dba8f7-7dcd-4a79-8aea-7594b47f7b8b)'
    backendAzureRmResourceGroupName: 'resourcegroup-tfstate'
    backendAzureRmStorageAccountName: 'saterraformtfstateskip'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform.tfstate'
  